### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by sylware** [dutchcoders/transfer.sh#614] opened 2024-04-19 01:54 UTC
I am trying to upload with curl a fixed libSDL3.so.0 for dota2 (alsa audio fixed), the upload goes ok but then I get 500 Internal Server Error
Could not save metadata

google does not give me any clues.

**Comment by stefanbenten** [comment] 2024-04-19 09:56
Duplicate of #594

**Closed by stefanbenten** 2024-04-19 09:56 UTC
