### ISSUE TITLE
Official instance: upload fails with 500

### ISSUE THREAD

**Issue by fancsali** [dutchcoders/transfer.sh#618] opened 2024-05-08 17:00 UTC
Wanted to give it a go, and on the web interface it says "500"; trying the command line the output is: "Could not save metadata".

**Comment by BartBruininks** [comment] 2024-06-20 09:05
Same, also from terminal for me.

**Comment by stefanbenten** [comment] 2024-06-20 18:18
Duplicate of https://github.com/dutchcoders/transfer.sh/issues/594

**Closed by stefanbenten** 2024-06-20 18:18 UTC
