### ISSUE TITLE
Uploading seems to no longer work.

### ISSUE THREAD

**Issue by BartBruininks** [dutchcoders/transfer.sh#622] opened 2024-06-20 09:04 UTC
I have been having this issue for a week/month? or two now, uploading seems to no longer work. It does not matter if it is uploaded by a terminal command, or by using the browse option on transfer.sh

Cheers,

Bart

**Comment by stefanbenten** [comment] 2024-06-20 18:19
Duplicate of https://github.com/dutchcoders/transfer.sh/issues/594

**Closed by stefanbenten** 2024-06-20 18:19 UTC
