### ISSUE TITLE
Question: In Debian11 v1.3.0 does not recognize the type

### ISSUE THREAD

**Issue by wc7086** [dutchcoders/transfer.sh#401] opened 2021-08-19 15:03 UTC
When running transfersh in Debian11, many formats are not recognized, but not all formats are not recognized.

![image](https://user-images.githubusercontent.com/74053663/130092654-7c60b720-31f7-41b2-abab-04714cdec440.png)

**Comment by aspacca** [comment] 2021-08-19 17:38
how did you upload the file?

**Comment by wc7086** [comment] 2021-08-19 17:56
> how did you upload the file?

Using web upload, uploading the same file in the old version will not have this problem.

**Comment by aspacca** [comment] 2021-08-19 18:57
I cannot reproduce, could you share the file?
mime type is inferred by the file extension: https://github.com/dutchcoders/transfer.sh/blob/master/server/handlers.go#L513

can you send a screenshot of the PUT request from network tab in the browser?

**Comment by wc7086** [comment] 2021-08-20 13:47
> I cannot reproduce, could you share the file?

[sample.gz](https://github.com/dutchcoders/transfer.sh/files/7021881/sample.gz)
http://transfer.sh/1xqzAJ2/%E6%9E%97%E7%A9%86%20-%20%E5%B0%84%E9%9B%95%E8%8B%B1%E9%9B%84%E4%BC%A0.mp3

> can you send a screenshot of the PUT request from network tab in the browser?

![image](https://user-images.githubusercontent.com/74053663/130243037-e4a70efd-23c5-4414-9519-3ea770a6879d.png)

**Comment by wc7086** [comment] 2021-08-20 14:05
![image](https://user-images.githubusercontent.com/74053663/130245497-69373b4b-1689-474d-a429-303892cf6162.png)

I found that gz files will not show the type either.

**Comment by wc7086** [comment] 2021-08-21 03:45
I tried several formats again and found that none of them could be recognized. There is a problem with the recognition format. I use Edge `92.0.902.78`.

**Comment by wc7086** [comment] 2021-08-21 03:59
When I upload zip in v1.2.6, the format will become `application/zip`.
https://transfer.sh/1pTGcQB/test.zip

**Comment by aspacca** [comment] 2021-08-21 09:56
I've tried all the files you sent me on my own instance with v1.3.0 and the type is correct.
What binary are you using?
I've installed https://github.com/dutchcoders/transfer.sh/releases/download/v1.3.0/transfersh-v1.3.0-linux-amd64
Can you try locally?

**Comment by wc7086** [comment] 2021-08-21 11:24
> Can you try locally?

Sorry, I forgot to mention my system version. After testing. This problem seems to only reproduce on Debian 11.

**Comment by wc7086** [comment] 2021-08-21 11:31
When running transfersh in Debian11, many formats are not recognized, but not all formats are not recognized.

**Comment by aspacca** [comment] 2021-08-21 12:55
https://play.golang.org/p/wiKZKLyeLrK

on unix go reads the mime type from this set of files:
https://github.com/golang/go/blob/go1.16.7/src/mime/type_unix.go#L19-L24

without proper content of those files only these are the extension with results:
https://github.com/golang/go/blob/go1.16.7/src/mime/type.go#L60-L76

what do you have on your system?

**Comment by wc7086** [comment] 2021-08-21 13:23
> what do you have on your system?

I used `find / -name mime.types` and I did not find `mime.types` in the Debian11 system.

**Comment by aspacca** [comment] 2021-08-21 13:29
```
# dpkg -S /etc/mime.types
media-types: /etc/mime.types
```

try to install `media-types` package

**Comment by wc7086** [comment] 2021-08-21 13:35
> dpkg -S /etc/mime.types

Use this command to prompt `dpkg-query: no path found matching pattern /etc/mime.types`. After searching, I found that `apt install media-types` should be used.

**Comment by wc7086** [comment] 2021-08-21 13:36
> try to install `media-types` package

Okay, the debian11 mirror does not include the `media-types` package by default. I now installed the `media-types` package to solve this problem.

**Comment by aspacca** [comment] 2021-08-22 09:54
can I close the issue @wc7086 ?

**Closed** 2021-08-22 10:43 UTC
