### ISSUE TITLE
transfer.sh shasum of upload and download not matching

### ISSUE THREAD

**Issue by hgezim** [dutchcoders/transfer.sh#569] opened 2023-06-23 16:21 UTC
You can check by looking at the `shasum` of a file you upload and what you download.

**Comment by hgezim** [comment] 2023-06-24 05:39
Downloading a file in Firefox gives me a different shasum number as well as a warning from FF:
<img width="599" alt="Xnip2023-06-23_23-38-06" src="https://github.com/dutchcoders/transfer.sh/assets/124675/4b539eff-aa2c-432d-b2c9-67c523cc1442">

**Comment by stefanbenten** [comment] 2023-06-28 01:35
Could you kindly upload a file and either send it via the support link on the homepage or link it here that shows this problem?
We have tried it on several machines now and cannot reproduce.

**Comment by hgezim** [comment] 2023-07-05 20:02
Can't reproduce at this point. It was a .tar.gz file for what it's worth.

**Comment by stefanbenten** [comment] 2023-07-06 21:04
If you are fine with it, i would recommend to close the issue for now until you can reproduce it again 👍

**Closed** 2023-07-06 21:05 UTC
