### ISSUE TITLE
transfer.sh is down

### ISSUE THREAD

**Issue by srikanthbojja** [dutchcoders/transfer.sh#589] opened 2023-11-21 09:32 UTC
Looks like transfer.sh service is down since morning.
any update?

**Comment by srikanthbojja** [comment] 2023-11-21 12:10
It is back up again, thanks. Please close this ticket

**Comment by srikanthbojja** [comment] 2023-11-22 14:10
the service is down again since morning CET

**Comment by stefanbenten** [comment] 2023-11-22 14:57
I can confirm, we are looking into some abuse details and are having the service unavailable during this time.

**Comment by cayenne17** [comment] 2023-11-23 10:49
transfer.sh is back

**Comment by KaKi87** [comment] 2023-12-28 11:40
Hi, although the site is up, all upload attempts fail with error 500. Thanks

**Comment by cayenne17** [comment] 2023-12-28 12:05
> Hi, although the site is up, all upload attempts fail with error 500. Thanks
Hi,
a issue has been opened: 
https://github.com/dutchcoders/transfer.sh/issues/594

**Comment by qzmtch** [comment] 2023-12-29 00:01
> I can confirm, we are looking into some abuse details and are having the service unavailable during this time.

And for users with RU IP, access to the service was fundamentally blocked? Or is it the hosting that is blocking access to the site?

**Comment by stefanbenten** [comment] 2023-12-31 14:03
> > I can confirm, we are looking into some abuse details and are having the service unavailable during this time.
> 
> And for users with RU IP, access to the service was blocked on principle? Or is it the hosting that is blocking access to the site?

It is geoblocking abusing countries of various kinds.

**Comment by Ever4engel** [comment] 2024-01-14 13:27
Seem the website is down again

**Comment by cayenne17** [comment] 2024-01-14 18:14
> Seem the website is down again

uploading to transfer.sh has not worked for almost 1 month

**Comment by dhavalsingh** [comment] 2024-01-17 05:33
Indian IPs might also be blocked, not working for me.

**Comment by cayenne17** [comment] 2024-01-17 10:10
from operator FR Free (AS12322) did not work for me

**Comment by mbenencase** [comment] 2024-01-17 22:20
I'm in Brazil, I can't use it as well

**Comment by GangstaPichu** [comment] 2024-01-19 06:56
I can't use it either and I'm from the US.

**Comment by acastillorobles77** [comment] 2024-01-19 23:59
transfer.sh seems to be currently down

**Comment by tobbi** [comment] 2024-01-22 00:44
It seems to be working again on my end.

**Comment by cayenne17** [comment] 2024-01-22 08:56
> It seems to be working again on my end.

same since Saturday

**Comment by stefanbenten** [comment] 2024-01-22 09:08
Closing, since service has been restored. As soon as abuse is detected, we will suspend service again 👍

**Closed by stefanbenten** 2024-01-22 09:08 UTC

**Comment by cayenne17** [comment] 2024-01-22 09:15
> Closing, since service has been restored. As soon as abuse is detected, we will suspend service again 👍

@stefanbenten 

Would it be possible to whitelist trusted IPs?

What you call abuse is
- too many mailings?
- Sending unwanted software?

**Comment by Sierra410** [comment] 2025-01-09 00:03
Oh, I'm self-hosting things, alright. I just remember this being a useful solution I could recommend to other people, or use myself when I don't have access to my own servers.

If it's down due to it being impossible to moderate, perhaps announce that the service is down for that reason? E.g. on the home page? Which is not even loadable as of now.

"Geoblocking abusing countries of various kinds" is an vague statement that sounds like a claim that entire countries just _randomly conspire_ to start abusing this service in particular, which makes no sense. Who says something like that?

I don't know the exact numbers, but assuming that most abuse (by which I mean malware, in this example, not copyright infringements. That'd be higher for poorer countries, naturally) comes from malware and that it's spread across the world more or less uniformly, countries with higher abuse % would be just countries in which the service is less popular among real people.

For example, if you ban the entirely of US or Canada or some other country, people there would learn that they can't rely on the service and would stop trying to use it (or they'd not learn about it in the first place, since even the homepage can't be viewed). Now, if you then un-ban that region one day, next to 100% of the traffic would be traffic generated by malware which automatically tries to use the service to spread itself.

It's sort of a self-fulling prophesy, so to say.

So, a single number that's illicit/legit traffic ratio for a region in isolation doesn't really say anything about the region in question.

And even if there is a measurable increase in abuse, there are more granular ways to filter traffic. For example regions which have slightly high abuse rates could be forced to complete a captcha (breaking curl support, but allowing use through a browser). If the rates are higher than that, the region could be banned from uploading, but not downloading. And if there's a legitimate state-sponsored attack or malware targeting a specific country, only then would a complete block make sense.

**Comment by aspacca** [comment] 2025-01-09 21:18
https://github.com/dutchcoders/transfer.sh?tab=readme-ov-file#disclaimer

I'm locking the issue, and please everyone just the readme
