### ISSUE TITLE
[SERVER ISSUE] HTTP Stream Closed Unexpectedly due to Protocol Error

### ISSUE THREAD

**Issue by EMREOYUN** [dutchcoders/transfer.sh#541] opened 2023-04-03 20:55 UTC
![image](https://user-images.githubusercontent.com/35144629/229625393-1437a4a7-160b-4ab1-b2ce-a60f30fad1d8.png)

**Comment by stefanbenten** [comment] 2023-04-03 22:57
Hello, this is a duplicate of https://github.com/dutchcoders/transfer.sh/issues/450 and likely due to unfortunate geoblocking of certain countries that abused the service.

**Closed by stefanbenten** 2023-04-03 22:57 UTC
